
logging.level:
    com.elchworks: info
    # suppress info logs of portfolio
#    com.elchworks.tastyworkstaxcalculator.portfolio: info
    com.elchworks.tastyworkstaxcalculator.convert: warn
    # com.elchworks.tastyworkstaxcalculator.TransactionCsvReader: debug
#    com.elchworks.tastyworkstaxcalculator.fiscalyear.FiscalYear: info
logging:
  pattern:
    console: "%5level %-40logger{39} : %m%n"
